services:

  postgres:
    image: postgres:latest
    container_name: cont1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5435:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

