spring:
  main:
    banner-mode: off
  application:
    name: practice5

  sql:
    init:
      mode: never
      schema-locations: classpath*:/databaseSQL.sql

  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false

  docker:
    compose:
      enabled: true
      lifecycle-management: start_only
      start:
        log-level: info
        command: up

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
